# Generated by Django 5.0.4 on 2024-05-06 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='queue_id',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
