# Generated by Django 5.0.4 on 2024-05-13 09:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0007_analytics'),
    ]

    operations = [
        migrations.AddField(
            model_name='analytics',
            name='time_c',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='analytics',
            name='time_u',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
