# Generated by Django 5.0.4 on 2024-05-13 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0010_delete_counter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analytics',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='analytics',
            name='processing_duration',
        ),
        migrations.RemoveField(
            model_name='analytics',
            name='processing_status',
        ),
    ]
