# Generated by Django 5.0.4 on 2024-05-15 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_admin', '0011_remove_analytics_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analytics',
            name='is_university',
            field=models.BooleanField(default=True),
        ),
    ]
